apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-demo-limits
  labels:
    app: go-api-demo-limits
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api-demo-limits
  template:
    metadata:
      labels:
        app: go-api-demo-limits
    spec:
      containers:
      - name: go-api-demo
        image: lcostea/go-api-demo:0.1.0
        ports:
        - containerPort: 3000
          name: http